site_name: Linux
site_url: https://jasper-zanjani.github.io/linux
theme:
  name: material
  favicon: img/logo.png
  logo: img/logo.png
  palette:
    scheme: slate
    primary: yellow
    accent: yellow
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.prune
  # - navigation.tabs         # Render top-level sections as a menubar
  # - navigation.tabs.sticky  # Top-level menubar remains visible while scrolling down
  # - navigation.indexes      # Integrate section index pages into sections as overview pages (incompatible with toc.integrate)
    # - navigation.sections     # Render sections as groups
    - toc.integrate           # Always render table of contents as part of the left navbar
    - content.code.annotate
    - content.code.copy
  shortcuts:
    search: 191
extra_javascript:
- assets/javascripts/custom.129bd6ad.min.js
extra_css:
- assets/stylesheets/custom.00c04c01.min.css
- style/annotation-width.css
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - meta
  - pymdownx.details
  - pymdownx.emoji: # from https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#emoji
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
