---

config:
  logLevel: 'debug'
  theme: 'default'
  themeVariables:
    darkMode: 'false'
    theme: 'base'
    cScale0: '#DDA77B'
    cScaleLabel0: '#000000'
    cScaleInv0: '#000000'
    cScale1: '#DBD8AE'
    cScaleLabel1: '#000000'
    cScale2: '#8DE4FF'
    cScaleLabel2: '#000000'


---

timeline
  section Pre-Merge
    2017 : Byzantium
    2021 : Constantinople : London
  section Merge
    2022 : The Merge
  section Post-Merge
  2023 : Shapella
  2024 : Dencun
  2025 : Pectra
  2026 : Fusaka
