.TH "Title header" 1 "25 June 2025" "0.1"
.SH "Section heading"
.PP
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut fringilla ante vel vulputate blandit. Morbi non sollicitudin tellus. Integer a eleifend libero. Pellentesque sit amet risus congue, rhoncus velit vel, fermentum nisi. Etiam quam ligula, finibus non hendrerit at, auctor sed ipsum. Cras scelerisque nibh neque, in dictum nisl egestas congue. Fusce et odio tincidunt, finibus nibh sed, vestibulum arcu. Quisque libero tortor, suscipit mollis tellus in, volutpat tristique enim. Mauris rhoncus ipsum eget velit finibus aliquam. Curabitur sed odio id massa imperdiet faucibus. Etiam ipsum eros, imperdiet quis erat convallis, pulvinar egestas felis. Quisque ac faucibus urna, non laoreet enim. 
.SH SYNOPSIS
Demonstration of manpage syntax
.B [-d] [-e] [-f
.I filename
.B ]
