import = ["/home/jasper/.config/alacritty/themes/toml/challenger_deep.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.normal]
family = "InconsolataNerdFont"

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "F11"

[selection]
save_to_clipboard = true

[window]
decorations = "full"
decorations_theme_variant = "Dark"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 83
lines = 22

[window.padding]
x = 20
y = 20
